spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PhoneShop
    username: postgres
    password: pospassword
  jpa:
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false